
stages:
  - build
  - deploy

build-hugo:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  stage: build
  artifacts:
    paths:
      - public/
  variables:
    TZ: Europe/Berlin
  image: docker.io/hugomods/hugo:base-0.147.2
  script:
    - hugo --minify --destination ./public

deploy-rsync:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  needs:
    - build-hugo
  stage: deploy
  image: docker.io/library/alpine:20250108
  variables:
    TARGET_PATH: /webroot/adora.codes
    RSYNC_TARGET_PORT: 2003
  before_script:
    - apk add --update --no-cache openssh rsync git tree
    - mkdir -p "$HOME/.ssh"
    - mv "$SSH_KEY_FILE" "$HOME/.ssh/id_ed25519"
    - chmod 0600 "$HOME/.ssh/id_ed25519"
    - ssh-keyscan -t ed25519 -p "$RSYNC_TARGET_PORT" "$RSYNC_TARGET_SERVER" >> "$HOME/.ssh/known_hosts"
  script:
    - rsync -avh -e "ssh -p $RSYNC_TARGET_PORT" --delete ./public/ "$RSYNC_TARGET_USER@$RSYNC_TARGET_SERVER:$TARGET_PATH"
