# Redirect netlify alias

[[redirects]]
  from = "https://personal-website-40cb76.netlify.app/"
  to = "https://adora.codes/"
  status = 301

[[redirects]]
  from = "https://personal-website-40cb76.netlify.app/*"
  to = "https://adora.codes/"
  status = 301