steps:
  build:
    image: golang:1.21-bookworm
    environment:
      - HUGO_VERSION=0.120.4
      - TZ=Europe/Berlin
    when:
      - event: push
        branch: [main, staging] 
    commands:
      - wget https://github.com/gohugoio/hugo/releases/download/v$${HUGO_VERSION}/hugo_extended_$${HUGO_VERSION}_linux-amd64.deb && apt install ./hugo_extended_$${HUGO_VERSION}_linux-amd64.deb && rm -f hugo_extended_$${HUGO_VERSION}_linux-amd64.deb
      - hugo --minify --destination ./public

  deploy-staging:
    # image: node:alpine
    image: lauralani/netlify-cli:latest
    pull: true
    when:
      - event: push
        branch: staging
    secrets:
      - NETLIFY_AUTH_TOKEN
      - NETLIFY_SITE_ID
    commands:
      # - npm install netlify-cli -g
      - netlify deploy --alias stage --dir ./public


  deploy-production:
    # image: node:alpine
    image: lauralani/netlify-cli:latest
    pull: true
    when:
      - event: push
        branch: main
    secrets:
      - NETLIFY_AUTH_TOKEN
      - NETLIFY_SITE_ID
    commands:
      # - npm install netlify-cli -g
      - netlify deploy --prod --dir ./public
